name: CI

on:
  workflow_dispatch:

  push:
    branches:
      - 'master'
      - 'main'
    paths-ignore:
      - '**.md'

# Cancel last CI if new commit come
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Runner:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install --force

      - name: Lint and Types
        run: |
          npm run lint
          npm run type:check

      - name: Build Firefox Release
        run: npm run bundle:firefox

      - name: Build Firefox Beta
        run: npm run bundle:firefox:beta

      - name: Package
        run: npm run pack-zip

      - name: Upload Release Assets
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/yuque-firefox-extension-*.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

